### PR TITLE
fix: pass namespace qualifier to Kubernetes API

### PR DESCRIPTION
**Pull request by pdecat**
This PR makes the plugin pass the namespace qualifier to the kubernetes API client when querying namespace scoped resources.

### CODE REVIEW

**Comment by beudbeud** [comment]
fix #180

**Comment by pdecat** [comment]
> fix #180

I didn't reference that issue because I believe it is different in that it is about plugin configuration, and not namespace handling in queries.

**Comment by beudbeud** [comment]
> > fix #180
> 
> I didn't reference that issue because I believe it is different in that it is about plugin configuration, and not namespace handling in queries.

my bad sorry

**Comment by pdecat** [comment]
It doesn't change the results at all. If namespace is used in query, results were filtered the same, just on the client side.

**Comment by bigdatasourav** [comment]
Hey @pdecat, we are handling the namespace filter using the field selector - https://github.com/turbot/steampipe-plugin-kubernetes/blob/main/kubernetes/utils.go#L632. It breaks when there is a permission scope issue. Thanks for the changes.

Could you please update the `kubernetes_pod_template` table as well and remove [this](https://github.com/turbot/steampipe-plugin-kubernetes/blob/main/kubernetes/utils.go#L639) condition, as it is no longer required to filter the namespace using the field selector?

**Comment by pdecat** [comment]
Hi @bigdatasourav, I believe I already made the change for `kubernetes_pod_template`: https://github.com/turbot/steampipe-plugin-kubernetes/pull/181/files#diff-667ea71f1dd70eee3db1f332c12fb05c280cbcfef2dde38e03a538f0df35ec27R128

Or are you thinking about something else?

I'll remove the field selector filter.

**Review by bigdatasourav — APPROVED** [review]
LGTM

**Review by misraved — APPROVED** [review]

**Pull request merged**
