### PR TITLE
Add KUBECONFIG env variable support in the plugin

### PR DESCRIPTION
**Pull request by bigdatasourav**
# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

### CODE REVIEW

**Comment by jacksgt** [comment]
Very much appreciated, as a new user I find this is quite confusing!

**Comment by cbruno10** [comment]
@Sourav What does the Kube SDK, kubtctl tool, and other Kube related tooling like the TF provider do in terms of env variable and order of precedence?

**Comment by bigdatasourav** [comment]
@cbruno10 by default, the kubectl tool looks for ~/.kube/config file; we can set a different file path by using the KUBECONFIG env variable. https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/.

TF does support KUBE_CONFIG_PATH(To provide a single path) and KUBE_CONFIG_PATHS(To provide multiple paths). https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs.

The Kube SDK does support KUBECONFIG as a [RecommendedConfigPathEnvVar](https://github.com/kubernetes/client-go/blob/ebad5fbb0d96ae12547fd19468316a604bce5ccf/tools/clientcmd/loader.go#LL164C27-L164C54) in the NewDefaultClientConfigLoadingRules method, which we have used in this PR. This method loads the default config setup and returns ClientConfigLoadingRules as a loader object. Earlier, we were directly initialising the [ClientConfigLoadingRules](https://github.com/turbot/steampipe-plugin-kubernetes/blob/main/kubernetes/utils.go#L436) object.

**Comment by cbruno10** [comment]
@bigdatasourav Do you know where we originally found the KUBERNETES_MASTER env variable?

Also, are there any other behaviour differences between the old and new SDK functions you mentioned beside the KUBECONFIG env variable being used now? Does the order of env var loading change? Are there additional validations or checked kubeconfig locations included now?

**Comment by bigdatasourav** [comment]
We currently offer The following parameters for specifying the configuration file path in either the SPC file or environment variables. The order of precedence is as follows:

config_path
config_paths
KUBE_CONFIG_PATHS
KUBERNETES_MASTER

Questions based on the above -
Are the paths config arg and env var useful (I think not)?
Should we keep Terraform ENV vars (I think yes, but the singular one - KUBE_CONFIG_PATHS)?
Should KUBECONFIG be the first env var (I think yes)?
Should we use KUBERNETES_MASTER,  which is already deprecated (I think not)?

Here is the updated and proposed order for the configuration file path:
config_path
KUBECONFIG
KUBE_CONFIG_PATH

@johnsmyth, Could you please share your thoughts on the above?

**Comment by bigdatasourav** [comment]
@johnsmyth kubectl does not honor KUBE_CONFIG_PATH or KUBE_CONFIG_PATHS, these are [Terrafrom](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) env vars. Should we remove them as well?

**Comment by bigdatasourav** [comment]
We are going to provide config path parameter support in the following order - 
config_path
config_paths (deprecated, will be removed after next month, please use config_path instead)
KUBECONFIG (New env var support. Plugin will prioritize KUBECONFIG if any other env var is also available)
KUBE_CONFIG_PATH (New env var support)
KUBE_CONFIG_PATHS (deprecated, will be removed after next month, please use KUBECONFIG or KUBE_CONFIG_PATH instead)
KUBERNETES_MASTER (deprecated, will be removed after next month, please use KUBECONFIG or KUBE_CONFIG_PATH instead)

**Review by misraved — APPROVED** [review]

**Pull request merged**
