### PR TITLE
Recompile plugin with steampipe-plugin-sdk v5.10.1

### PR DESCRIPTION
**Pull request by burahimu**
By updating the sdk version the following [bug fix](https://github.com/turbot/steampipe-plugin-sdk/commit/c3322c570012c4ddf93999d5eb46a017f135d933) is included.

After update, I don't have the `runtime error` anymore. It fixes https://github.com/turbot/steampipe-plugin-kubernetes/issues/224

### CODE REVIEW

**Comment by burahimu** [comment]
**question:** there is any doc that says how to run test? 

I want to include the Connection Key Column `context_name` to ensure that everything works when running an SQL query.

**Comment by ParthaI** [comment]
Hello @burahimu, I apologize for the inconvenience. There was a bug in Steampipe SDK `v5.10.0` which has been fixed in `v5.10.1`. Thank you for submitting the PR and for your contribution.

**Comment by burahimu** [comment]
> Hello @burahimu, I apologize for the inconvenience. There was a bug in Steampipe SDK `v5.10.0` which has been fixed in `v5.10.1`. Thank you for submitting the PR and for your contribution.
> 
> We don't have a proper doc to test connection key quals yet. We need to run the query as follows:
> 
> * In your `~/.steampipe/config/kubernetes.spc` file must have aggregator connection setup.
> * Please try the following query against the aggregator connection to test it out.
> 
> ```sql
> select
>   hc.name as chart_name,
>   hc.type as chart_type,
>   hc.version as chart_version,
>   hr.name as release_name,
>   hr.status as release_status,
>   hr.version as deployment_version,
>   hr.first_deployed as deployed_at,
>   hr.config as deployment_config
> from
>   agg_con.helm_chart as hc
>   left join agg_con.helm_release as hr
>     on hc.name = hr.chart_name
> where
>   hr.status = 'deployed'
>   and hc.context_name = hr.context_name;
> ```
> 
> Note: `agg_con` is an aggregator connection for the kubernetes plugin.

Thanks for the reply.

It's proper to the developer to have a kube context available? Is it not integrated to run a local cluster (i.e: [kind](https://kind.sigs.k8s.io/))

**Comment by ParthaI** [comment]
Hi @burahimu,
- Yes, a developer typically needs to have a kube context available to interact with any Kubernetes cluster, whether it is a local cluster or a remote one.
- The kube context is necessary for `kubectl` and other Kubernetes tools to know which cluster to interact with and which credentials to use.
- When you create a cluster with `kind`, it automatically updates your kubeconfig file with the context for the new cluster.
- You can see the context details for the local cluster with the help of `kubectl config get-contexts` command.

Sure, here's the sentence rewritten in a more polite manner:

I haven't experimented much with local clusters yet, but feel free to give it a try.

Thanks!

**Review by misraved — APPROVED** [review]

**Pull request merged**
